# Generated by Django 6.0.2 on 2026-03-04 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse_app', '0002_alter_department_id_alter_emergencyuser_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(choices=[('chuda', 'Chuda'), ('chuda_centre', 'Chuda Centre'), ('chuda_estate', 'Chuda Estate'), ('kizingo', 'Kizingo'), ('miritini', 'Miritini'), ('tononoka', 'Tononoka'), ('kipevu', 'Kipevu'), ('ganjoni', 'Ganjoni'), ('magongo', 'Magongo')], default='chuda', max_length=100)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
