# Generated by Django 6.0.2 on 2026-03-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse_app', '0004_incident_reported_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='location_name',
            field=models.CharField(choices=[('Tudor', 'Tudor'), ('Tudor_centre', 'Tudor Centre'), ('Tudor_estate', 'Tudor Estate'), ('kizingo', 'Kizingo'), ('miritini', 'Miritini'), ('tononoka', 'Tononoka'), ('kipevu', 'Kipevu'), ('ganjoni', 'Ganjoni'), ('magongo', 'Magongo')], default='Mombasa Chuda', max_length=255),
        ),
        migrations.AlterField(
            model_name='emergencyuser',
            name='location',
            field=models.CharField(choices=[('Tudor', 'Tudor'), ('Tudor_centre', 'Tudor Centre'), ('Tudor_estate', 'Tudor Estate'), ('kizingo', 'Kizingo'), ('miritini', 'Miritini'), ('tononoka', 'Tononoka'), ('kipevu', 'Kipevu'), ('ganjoni', 'Ganjoni'), ('magongo', 'Magongo')], default='Tudor', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('Tudor', 'Tudor'), ('Tudor_centre', 'Tudor Centre'), ('Tudor_estate', 'Tudor Estate'), ('kizingo', 'Kizingo'), ('miritini', 'Miritini'), ('tononoka', 'Tononoka'), ('kipevu', 'Kipevu'), ('ganjoni', 'Ganjoni'), ('magongo', 'Magongo')], default='Tudor', max_length=100),
        ),
    ]
