# Generated by Django 6.0.2 on 2026-03-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse_app', '0005_alter_department_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='location_name',
            field=models.CharField(blank=True, choices=[('Tudor', 'Tudor'), ('Tudor_centre', 'Tudor Centre'), ('Tudor_estate', 'Tudor Estate'), ('kizingo', 'Kizingo'), ('miritini', 'Miritini'), ('tononoka', 'Tononoka'), ('kipevu', 'Kipevu'), ('ganjoni', 'Ganjoni'), ('magongo', 'Magongo')], max_length=255),
        ),
    ]
