# Generated by Django 6.0.2 on 2026-03-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse_app', '0006_incident_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='location_name',
            field=models.CharField(choices=[('Tudor', 'Tudor'), ('Tudor_centre', 'Tudor Centre'), ('Tudor_estate', 'Tudor Estate'), ('kizingo', 'Kizingo'), ('miritini', 'Miritini'), ('tononoka', 'Tononoka'), ('kipevu', 'Kipevu'), ('ganjoni', 'Ganjoni'), ('magongo', 'Magongo')], max_length=255),
        ),
    ]
