# Generated by Django 6.0.2 on 2026-03-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse_app', '0008_alter_department_latitude_alter_department_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
