# Generated by Django 6.0.2 on 2026-03-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse_app', '0012_alter_incident_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('fire', 'Fire Department'), ('medical', 'Medical/Ambulance'), ('police', 'Police Department'), ('general rescue', 'General Department')], max_length=100),
        ),
    ]
