# Generated by Django 6.0.2 on 2026-03-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse_app', '0013_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('fire', 'Fire Department'), ('medical', 'Medical Department'), ('police', 'Police Department'), ('general', 'General Department')], max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location_name',
            field=models.CharField(blank=True, choices=[('Tudor', 'Tudor'), ('Tudor_centre', 'Tudor Centre'), ('Tudor_estate', 'Tudor Estate'), ('kizingo', 'Kizingo'), ('miritini', 'Miritini'), ('tononoka', 'Tononoka'), ('kipevu', 'Kipevu'), ('ganjoni', 'Ganjoni'), ('magongo', 'Magongo')], max_length=255, null=True),
        ),
    ]
