# Generated by Django 6.0.2 on 2026-05-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse_app', '0017_alter_department_id_alter_emergencyuser_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
