# Generated by Django 6.0.2 on 2026-03-09 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse_app', '0007_alter_department_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='latitude',
            field=models.FloatField(blank=True, default=-4.0435, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='longitude',
            field=models.FloatField(blank=True, default=39.6682, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergencyresponse_app.profile'),
        ),
    ]
