# Generated by Django 6.0.2 on 2026-03-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse_app', '0009_alter_incident_latitude_alter_incident_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='longitude',
        ),
    ]
