# Generated by Django 6.0.2 on 2026-03-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse_app', '0011_incident_latitude_incident_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
