# Generated by Django 6.0.2 on 2026-05-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse_app', '0014_alter_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responder',
            name='is_available',
        ),
        migrations.AddField(
            model_name='responder',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='available', max_length=20),
        ),
    ]
