# Generated by Django 6.0.2 on 2026-05-20 13:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse_app', '0018_assignmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentrequest',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_requests', to='emergencyresponse_app.incident'),
        ),
        migrations.AddField(
            model_name='assignmentrequest',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentrequest',
            name='responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_requests', to='emergencyresponse_app.responder'),
        ),
        migrations.AddField(
            model_name='assignmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentresponse',
            name='incident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='emergencyresponse_app.incident'),
        ),
        migrations.AddConstraint(
            model_name='assignmentrequest',
            constraint=models.UniqueConstraint(fields=('incident', 'responder'), name='unique_incident_responder_assignment'),
        ),
    ]
