# Generated by Django 6.0.2 on 2026-07-03 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse_app', '0020_assignmentrequest_dispatched_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('assignment', 'New Assignment'), ('update', 'Assignment Update'), ('alert', 'Alert')], default='assignment', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='emergencyresponse_app.assignmentrequest')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='emergencyresponse_app.incident')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='emergencyresponse_app.responder')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['responder', '-created_at'], name='emergencyre_respond_69727b_idx'), models.Index(fields=['responder', 'is_read'], name='emergencyre_respond_b16bf3_idx')],
            },
        ),
    ]
