# Generated by Django 6.0.2 on 2026-07-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse_app', '0021_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('department_admin', 'Department Admin'), ('responder', 'Responder')], default='responder', max_length=20),
        ),
    ]
