# Generated by Django 6.0.2 on 2026-07-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse_app', '0022_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('department_admin', 'Department Admin'), ('responder', 'Responder')], default='user', max_length=20),
        ),
    ]
