# Generated by Django 6.0.2 on 2026-07-10 08:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse_app', '0023_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responder',
            name='department',
        ),
        migrations.RemoveField(
            model_name='responder',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='responder',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emergencyresponse_app.department'),
        ),
        migrations.AddField(
            model_name='responder',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emergencyresponse_app.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('department_admin', 'Department Admin'), ('responder', 'Responder'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
