# Generated by Django 6.0.2 on 2026-07-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse_app', '0024_remove_responder_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, choices=[('Tudor', 'Tudor'), ('Tudor_centre', 'Tudor Centre'), ('Tudor_estate', 'Tudor Estate'), ('kizingo', 'Kizingo'), ('miritini', 'Miritini'), ('tononoka', 'Tononoka'), ('kipevu', 'Kipevu'), ('ganjoni', 'Ganjoni'), ('magongo', 'Magongo')], default='Tudor', max_length=100, null=True),
        ),
    ]
