# Generated by Django 6.0.2 on 2026-07-16 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse_app', '0025_alter_profile_emergency_contact_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='emergencyre_respond_69727b_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='emergencyre_respond_b16bf3_idx',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='assigned_responder',
        ),
        migrations.AlterField(
            model_name='assignmentrequest',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_requests', to='emergencyresponse_app.incident'),
        ),
        migrations.AlterField(
            model_name='assignmentrequest',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_requests', to='emergencyresponse_app.responder'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='assignment_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='emergencyresponse_app.assignmentrequest'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('assignment_request', 'Assignment Request'), ('assignment_accepted', 'Assignment Accepted'), ('assignment_declined', 'Assignment Declined'), ('incident_update', 'Incident Update'), ('alert', 'General Alert')], default='assignment_request', max_length=20),
        ),
        migrations.AddIndex(
            model_name='assignmentrequest',
            index=models.Index(fields=['status'], name='emergencyre_status_792da0_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentrequest',
            index=models.Index(fields=['created_at'], name='emergencyre_created_715367_idx'),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='incident',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='responder',
        ),
    ]
