# Generated by Django 6.0.2 on 2026-08-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse_app', '0026_remove_notification_emergencyre_respond_69727b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('assignment_accepted', 'Assignment Accepted'), ('assignment_rejected', 'Assignment Rejected'), ('assignment_expired', 'Assignment Expired'), ('incident_resolved', 'Incident Resolved')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emergencyresponse_app.department')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emergencyresponse_app.incident')),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emergencyresponse_app.responder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
